## sprint-3-T04
### Eloi Canals

[x] Nivell 1. Exercici 1. Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [12]:
import numpy as np

def statsarr(myarr):
    if myarr.ndim > 1:
        print(f"Error. Array te {myarr.ndim} dimensions.")
    else:
        print(f'Basic stats for: {myarr}')
        print(f'Data type is: {type(myarr)}')
        print(f'Shape is: {myarr.shape}')
        print(f'Max value is: {myarr.max()}')
        print(f'Min value is: {myarr.min()}')
        print(f'Array mean is: {myarr.mean().round(2)}')
        print(f'Array sum is: {myarr.sum()}')

array1 = np.array([242,3,54,756,5,7456,45,764567,456,745,444,8,6,3,452,3452,3])

statsarr(array1)

Basic stats for: [   242      3     54    756      5   7456     45 764567    456    745
    444      8      6      3    452   3452      3]
Data type is: <class 'numpy.ndarray'>
Shape is: (17,)
Max value is: 764567
Min value is: 3
Array mean is: 45805.71
Array sum is: 778697


[x] Nivell 1. Exercici 2. Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [33]:
def buildarr(arrsize):
        newarr = np.random.random((arrsize,arrsize))
        return newarr

myarr = buildarr(5)
print(f'My new array is: {myarr}')

My new array is: [[0.63516264 0.02343374 0.79708667 0.52608572 0.56453319]
 [0.50342835 0.42559896 0.02595854 0.14619117 0.39916286]
 [0.21251254 0.76784179 0.28988299 0.07626051 0.20412926]
 [0.38213415 0.01018104 0.8957677  0.19152116 0.1113254 ]
 [0.56851769 0.14888406 0.07296802 0.6440319  0.19433362]]


[x] Nivell 1. Exercici 3. Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [29]:
def totals(myarrt):
    totalsx = myarrt.sum(1)
    totalsy = myarrt.sum(0)
    return totalsx, totalsy

totx,toty = totals(myarr)
print('Totals per eix x:')
print(totx)
print('Totals per eix y:')
print(toty)

Totals per eix x:
[2.06549457 2.30116111 2.56305251 2.60700218 3.70466842]
Totals per eix y:
[2.71117828 2.5162451  2.16103251 2.96675877 2.88616414]


[x] Nivell 1. Exercici 4. Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [34]:
def mycoef(arrcoef):
    return np.corrcoef(arrcoef)

print(f'El coeficient de correlació de la matriu es: {mycoef(myarr)}')

El coeficient de correlació de la matriu es: [[ 1.         -0.47057312 -0.80579546  0.76148799  0.13775494]
 [-0.47057312  1.          0.31560158 -0.64819666  0.16208198]
 [-0.80579546  0.31560158  1.         -0.28670778 -0.57370652]
 [ 0.76148799 -0.64819666 -0.28670778  1.         -0.24349308]
 [ 0.13775494  0.16208198 -0.57370652 -0.24349308  1.        ]]
